### ISSUE TITLE
Asyncio related notimplementederror in Windows with Python 3.8 coming from zmq

### ISSUE THREAD

**Issue by ntouran** [terrapower/armi#175]
I'm getting some errors during doc building, specifically when sphinx builds the jupyter notebooks, with errors that look like this:

```
Notebook error:
NotImplementedError in tutorials\data_model.nblink:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\ntouran\venvs\ar38\lib\site-packages\nbclient\client.py", line 360, in _async_cleanup_kernel
    await ensure_async(self.kc.stop_channels())
  File "C:\Users\ntouran\venvs\ar38\lib\site-packages\jupyter_client\client.py", line 125, in stop_channels
    if self.shell_channel.is_alive():
  File "C:\Users\ntouran\venvs\ar38\lib\site-packages\jupyter_client\client.py", line 151, in shell_channel
    socket = self.connect_shell(identity=self.session.bsession)
  File "C:\Users\ntouran\venvs\ar38\lib\site-packages\jupyter_client\connect.py", line 561, in connect_shell
    return self._create_connected_socket('shell', identity=identity)
  File "C:\Users\ntouran\venvs\ar38\lib\site-packages\jupyter_client\connect.py", line 545, in _create_connected_socket
    sock = self.context.socket(socket_type)
  File "C:\Users\ntouran\venvs\ar38\lib\site-packages\zmq\sugar\context.py", line 226, in socket
    s = self._socket_class(self, socket_type, **kwargs)
  File "C:\Users\ntouran\venvs\ar38\lib\site-packages\zmq\_future.py", line 144, in __init__
    self._init_io_state()
  File "C:\Users\ntouran\venvs\ar38\lib\site-packages\zmq\asyncio\__init__.py", line 53, in _init_io_state
    self.io_loop.add_reader(self._fd, lambda : self._handle_events(0, 0))
  File "C:\users\ntouran\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
```

This looks like an issue related to [this documentation](https://docs.python.org/3/library/asyncio-platforms.html#windows) where this type of thing is just not supported in Windows. 

Looks like this is mostly a problem in our dependencies.

**Comment by ntouran** [comment]
Looks like there's a *very* related issue here: https://github.com/jupyter/nbconvert/issues/1372 with a workaround we can try.

**Comment by youngmit** [comment]
Is this fixed in #174 ?

**Comment by ntouran** [comment]
oh! yes it is fixed there. Thanks.

**Comment by perceptualrobots** [comment]
> oh! yes it is fixed there. Thanks.

How do I get this fix?

Do I need to "pip install" a particular version of a particular package?

**Comment by ntouran** [comment]
> How do I get this fix?

In your own project, just run code similar to [what's shown here](https://github.com/jupyter/nbconvert/issues/1372#issuecomment-691596163) during initialization.
