### ISSUE TITLE
Read FFTF project with armi-mac

### ISSUE THREAD

**Issue by sombrereau** [terrapower/armi#218]
Hi ARMI team,

I download the master branch of the armi for the ANS ARMI Workshop and failed to load the FFTF benchmark

Here is my traceback error:
```
(armi-venv) Cisneros@Anselmos-iMac armi-workshop % armi run FFTF.yaml
[warn] Failed to import psutil; MemoryProfiler will not provide meaningful data.

                       ---------------------------------------------------
                      |             _      ____     __  __    ___         |
                      |            / \    |  _ \   |  \/  |  |_ _|        |
                      |           / _ \   | |_) |  | |\/| |   | |         |
                      |          / ___ \  |  _ <   | |  | |   | |         |
                      |         /_/   \_\ |_| \_\  |_|  |_|  |___|        |
                      |         Advanced  Reactor  Modeling Interface     |
                       ---------------------------------------------------
                                      Version 0.1.5     

[info] Could not read stream in YAML format. Attempting XML format.
[CRIT 000 ] Unhandled exception in __main__ on local.
[CRIT 000 ] Stack trace: Traceback (most recent call last):
  File "/Users/Cisneros/venvs/armi-venv/lib/python3.8/site-packages/armi/settings/settingsIO.py", line 194, in readFromFile
    self.readFromStream(f, handleInvalids, self.format)
  File "/Users/Cisneros/venvs/armi-venv/lib/python3.8/site-packages/armi/settings/settingsIO.py", line 212, in readFromStream
    self._readXml(stream, handleInvalids=handleInvalids)
  File "/Users/Cisneros/venvs/armi-venv/lib/python3.8/site-packages/armi/settings/settingsIO.py", line 222, in _readXml
    tree = ET.parse(stream)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/xml/etree/ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 68, column 89

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Cisneros/venvs/armi-venv/lib/python3.8/site-packages/armi/__main__.py", line 35, in main
    code = ArmiCLI().run()
  File "/Users/Cisneros/venvs/armi-venv/lib/python3.8/site-packages/armi/cli/__init__.py", line 174, in run
    return self.executeCommand(args.command, args.args)
  File "/Users/Cisneros/venvs/armi-venv/lib/python3.8/site-packages/armi/cli/__init__.py", line 193, in executeCommand
    cmd.parse(args)
  File "/Users/Cisneros/venvs/armi-venv/lib/python3.8/site-packages/armi/cli/entryPoint.py", line 170, in parse
    self.parse_args(args)
  File "/Users/Cisneros/venvs/armi-venv/lib/python3.8/site-packages/armi/cli/entryPoint.py", line 131, in parse_args
    self.parser.parse_args(args, namespace=self.args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/argparse.py", line 2009, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/argparse.py", line 1965, in consume_positionals
    take_action(action, args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/argparse.py", line 1874, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Users/Cisneros/venvs/armi-venv/lib/python3.8/site-packages/armi/cli/entryPoint.py", line 326, in __call__
    cs.loadFromInputFile(values)
  File "/Users/Cisneros/venvs/armi-venv/lib/python3.8/site-packages/armi/settings/caseSettings.py", line 200, in loadFromInputFile
    reader.readFromFile(fName, handleInvalids)
  File "/Users/Cisneros/venvs/armi-venv/lib/python3.8/site-packages/armi/settings/settingsIO.py", line 196, in readFromFile
    raise exceptions.InvalidSettingsFileError(path, str(ee))
armi.localization.exceptions.InvalidSettingsFileError: Attempted to load an invalid settings file from: FFTF.yaml. not well-formed (invalid token): line 68, column 89
```

**Comment by ntouran** [comment]
Fascinating, thanks for the report!! [That input file](https://github.com/terrapower/fftf-isothermal-model/blob/master/FFTF.yaml) only has 24 lines so I wonder how it counted 68 lines.

Anyway the real error is hidden here because `armi.settings.settingsIO.SettingsReader.readFromStream` catches an exception and makes an assumption that it must be XML format if any error happened. This is obviously a bad assumption in this case. What we need to do is figure out what that exception actually is. 

Options:
* We find a good way to get a MacOS environment up as developers and test fixes there. 
* You put a `raise` statement right after `except ruamel.yaml.scanner.ScannerError:` and tell us what the *real* exception was.

**Comment by veeshy** [comment]
FWIW, this works on my Mac, OS X 10.15.6 (19G2021)

Largely clean env with a few outliers, perhaps most imp is running Python 3.7.6, armi 0.1.5
[mypipinstalled.txt](https://github.com/terrapower/armi/files/5662865/mypipinstalled.txt)

**Comment by partofthething** [comment]
Thanks for the info @veeshy!

**Comment by jakehader** [comment]
Is this still open @youngmit /@ntouran / @sombrereau ?

**Comment by jakehader** [comment]
Closing due to no response. I believe this has been fixed.
