### ISSUE TITLE
Documentation fails to build correctly with fresh install of environment

### ISSUE THREAD

**Issue by ntouran** [terrapower/armi#274]
I tried building the documentation with the latest versions of all our dependencies with a fresh virtual environment in Python 3.9 and ran into a few new errors that lead to the following effects. The errors show up on both Windows and Linux platforms:

* Pyreverse images of the reactor classes are broken in the built documentation
* Bullet lists and other lists fail to render anywhere in the docs

The new errors with recent versions of the dependencies include:

Lots of blueprints-related attribute errors for each object that uses blueprints of the form:

```
WARNING: autodoc: failed to import attribute 'NuclideFlag.__round_trip_data' from module 'armi.reactor.blueprints.isotopicOptions'; the following exception was raised:                                                                       
Traceback (most recent call last):
  File "/srv/armi39/lib/python3.9/site-packages/sphinx/util/inspect.py", line 393, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: type object 'NuclideFlag' has no attribute '_NuclideFlag__round_trip_data'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/armi39/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 111, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/srv/armi39/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 320, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/srv/armi39/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2604, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/srv/armi39/lib/python3.9/site-packages/sphinx/util/inspect.py", line 409, in safe_getattr
    raise AttributeError(name) from exc 
AttributeError: _NuclideFlag__round_trip_data
```
(this is likely related to the yamlize dependency)

A new pyreverse error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/srv/armi39/lib/python3.9/site-packages/pylint/pyreverse/main.py", line 231, in <module>
    Run(sys.argv[1:])
  File "/srv/armi39/lib/python3.9/site-packages/pylint/pyreverse/main.py", line 201, in __init__
    sys.exit(self.run(args))
  File "/srv/armi39/lib/python3.9/site-packages/pylint/pyreverse/main.py", line 219, in run
    diadefs = handler.get_diadefs(project, linker)
  File "/srv/armi39/lib/python3.9/site-packages/pylint/pyreverse/diadefslib.py", line 236, in get_diadefs
    diagrams = DefaultDiadefGenerator(linker, self).visit(project)
  File "/srv/armi39/lib/python3.9/site-packages/pylint/pyreverse/utils.py", line 210, in visit
    self.visit(local_node)
  File "/srv/armi39/lib/python3.9/site-packages/pylint/pyreverse/utils.py", line 207, in visit
    methods[0](node)
  File "/srv/armi39/lib/python3.9/site-packages/pylint/pyreverse/diadefslib.py", line 162, in visit_module
    self.linker.visit(node)
  File "/srv/armi39/lib/python3.9/site-packages/pylint/pyreverse/utils.py", line 210, in visit
    self.visit(local_node)
  File "/srv/armi39/lib/python3.9/site-packages/pylint/pyreverse/utils.py", line 207, in visit
    methods[0](node)
  File "/srv/armi39/lib/python3.9/site-packages/pylint/pyreverse/inspector.py", line 247, in visit_import
    relative = modutils.is_relative(name[0], context_file)
  File "/srv/armi39/lib/python3.9/site-packages/astroid/modutils.py", line 581, in is_relative
    parent_spec = importlib.util.find_spec(name, from_file)
  File "/usr/lib/python3.9/importlib/util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'reactor'
```

I'm not sure which of these, or something else, is responsible for the loss of enumeration/list bullets throughout the whole project. I tried downgrading `sphinx-rtd-theme` to `0.5.0` as a check and that still exhibited the issue. 

Reverting pylint back to `2.6.2` gets rid of these two errors, so they were likely introduced in pylint `2.7.0`, (pylint contains pyreverse) but the rendering errors still happen in the html, so these are apparently unrelated issues. 

Reverting sphinx itself back from `3.5.3` to `3.3.1` doesn't fix the html bullets either. 

AHA! Reverting from `docutils` `0.17` to `0.16` brings back the bullets!

**Comment by ntouran** [comment]
The Module import errors are related to this: https://github.com/PyCQA/pylint/issues/4186 and can be removed by reverting pylint.
