### ISSUE TITLE
Some gallery examples are broken

### ISSUE THREAD

**Issue by mgjarrett** [terrapower/armi#417]
Six of the gallery examples show a "broken" thumbnail.

https://terrapower.github.io/armi/gallery/index.html

Related to #394; some of these examples are calling a `sefl._log()` with arguments that are consistent with the ARMI logger where a standard python logger is expected.

```
Traceback (most recent call last):
  File "/home/runner/work/armi/armi/doc/gallery-src/framework/run_fuelManagement.py", line 31, in <module>
    o, reactor = test_reactors.loadTestReactor(inputFileName="refTestCartesian.yaml")
  File "/home/runner/work/armi/armi/armi/reactor/tests/test_reactors.py", line 176, in loadTestReactor
    o = operators.factory(cs)
  File "/home/runner/work/armi/armi/armi/operators/__init__.py", line 52, in factory
    return getOperatorClassFromSettings(cs)(cs)
  File "/home/runner/work/armi/armi/armi/operators/operator.py", line 110, in __init__
    reportingUtils.writeWelcomeHeaders(self, cs)
  File "/home/runner/work/armi/armi/armi/bookkeeping/report/reportingUtils.py", line 201, in writeWelcomeHeaders
    _writeCaseInformation(o, cs)
  File "/home/runner/work/armi/armi/armi/bookkeeping/report/reportingUtils.py", line 85, in _writeCaseInformation
    runLog.header("=========== Case Information ===========")
  File "/home/runner/work/armi/armi/armi/runLog.py", line 384, in header
    LOG.log("header", msg, single=single, label=label)
  File "/home/runner/work/armi/armi/armi/runLog.py", line 163, in log
    self.logger.log(msgLevel, msg, single=single, label=label)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/logging/__init__.py", line 1512, in log
    self._log(level, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'single'
```

**Comment by john-science** [comment]
@mgjarrett  I opened a PR for this:  https://github.com/terrapower/armi/pull/418

**Comment by john-science** [comment]
PR #418 resolved this ticket.
