### ISSUE TITLE
c5g7 tutorial case errors when plotting

### ISSUE THREAD

**Issue by veeshy** [terrapower/armi#53]
Working through https://terrapower.github.io/armi/user/tutorials/walkthrough_lwr_inputs.html with no edits to the inputs at the bottom of the page I got the following error. The ANL case worked fine, local tests passed. 

```
$ armi run c5g7-settings.yaml 

[impt] Beginning of BOL Reports
[err ] <class 'AttributeError'>\n'NoneType' object has no attribute 'getPitch'\<traceback object at 0x128243208>
[info] Writing to database for statepoint: /c00n00error
[CRIT 000 ] Unhandled exception in __main__ on local.
[CRIT 000 ] Stack trace: Traceback (most recent call last):
  File "/Users/veeshy/projects/armi/armi-venv/lib/python3.7/site-packages/armi/__main__.py", line 34, in main
    code = ArmiCLI().run()
  File "/Users/veeshy/projects/armi/armi-venv/lib/python3.7/site-packages/armi/cli/__init__.py", line 171, in run
    return self.executeCommand(args.command, args.args)
  File "/Users/veeshy/projects/armi/armi-venv/lib/python3.7/site-packages/armi/cli/__init__.py", line 197, in executeCommand
    return cmd.invoke()
  File "/Users/veeshy/projects/armi/armi-venv/lib/python3.7/site-packages/armi/cli/run.py", line 36, in invoke
    inputCase.run()
  File "/Users/veeshy/projects/armi/armi-venv/lib/python3.7/site-packages/armi/cases/case.py", line 347, in run
    o.operate()
  File "/Users/veeshy/projects/armi/armi-venv/lib/python3.7/site-packages/armi/operators/operator.py", line 204, in operate
    self._mainOperate()
  File "/Users/veeshy/projects/armi/armi-venv/lib/python3.7/site-packages/armi/operators/operator.py", line 210, in _mainOperate
    self.interactAllBOL()
  File "/Users/veeshy/projects/armi/armi-venv/lib/python3.7/site-packages/armi/operators/operator.py", line 407, in interactAllBOL
    self._interactAll("BOL", activeInterfaces)
  File "/Users/veeshy/projects/armi/armi-venv/lib/python3.7/site-packages/armi/operators/operator.py", line 292, in _interactAll
    halt = halt or interactMethod(*args)
  File "/Users/veeshy/projects/armi/armi-venv/lib/python3.7/site-packages/armi/bookkeeping/report/reportInterface.py", line 58, in interactBOL
    reportingUtils.makeCoreAndAssemblyMaps(self.r, self.cs)
  File "/Users/veeshy/projects/armi/armi-venv/lib/python3.7/site-packages/armi/bookkeeping/report/reportingUtils.py", line 986, in makeCoreAndAssemblyMaps
    fontSize=8,
  File "/Users/veeshy/projects/armi/armi-venv/lib/python3.7/site-packages/armi/reactor/reactors.py", line 1977, in plotFaceMap
    Flags.FUEL
AttributeError: 'NoneType' object has no attribute 'getPitch'
```

**Comment by youngmit** [comment]
Thanks for the report. I was able to reproduce this on my end, and there are a couple issues here. 
First, the C5G7 doesn't explicitly mark any of the blocks in the model as "fuel". Lots of things in ARMI try to find fuel blocks to do special things, and not having any official "fuel" blocks leads to trouble. We will update the example to fix this.

The other issue is that this error is happening in a plotting function. Unfortunately a lot of this kind of stuff in ARMI is implemented for fast reactors, which typically have hexagonal lattices. As such, this plotting function is assuming a hex geometry, which will also fail even if there are fuel blocks in the model. This will require a little more effort, to make the plotting function support different geometries.

There are a few things we can do:
 - Add fuel flags to the blocks in the model (I'll start doing that now)
 - Add a check in the plotting function to short-circuit if the model isn't a supported geometry (I can also do this now)
- Add support for more geometries. This will take a bit of developer effort, so we will have to discuss how we want to address this. We may be willing to do this in-house, but @veeshy if you wanted to take a stab at it, it might be a pretty good introductory task. Let us know if you're interested.

**Comment by veeshy** [comment]
While I would love to contribute one day, I'm scoping for a hex based reactor so I don't mind too much for more geometries (yet!). Thanks for the confirmation.

**Comment by ntouran** [comment]
Thanks @veeshy, we'll get the tutorial running. Looks like we can improve our testing to flag when this tutorial breaks for next time too.
