### ISSUE TITLE
Switch from coveralls.io to codecov.io

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#552]
# Reasoning

1. Recently, `coveralls.io` has broken a couple times and caused us build failures. On other projects, I have run `codecov.io` for years with no such problems.
2. `Coveralls.io` forces us to use a private GitHub security token. This is extra work we don't need to do with `codecov.io`. (Particularly since these tokens expire every 12 months, and we would need to keep people on top of that.)
3. `Codecov.io` will report any code coverage problems during a PR by opening a comment on the PR page. This is particularly handy, as developers can get a nice GUI explaining what lines of code they missed in their coverage.

In the end, this is a low priority issue, since what we have now is working. **But**, this is also an exceptionally low-effort issue to fix, as `codecov.io` is all but automatic.

**Comment by ntouran** [comment]
I have no problem with that.

**Comment by john-science** [comment]
There have been a couple of minor outages with coverals.io this week.

I thought I was going to close this ticket AGAIN, but now I'm thinking maybe it's still relevant.

**Comment by john-science** [comment]
Okay, in the past 13 months, coveralls has been pretty stable. So I will close this ticket, and only reopen it if we have more issues.

**Comment by john-science** [comment]
I thought I was past this. But `coveralls.io` broke again today:

https://github.com/terrapower/armi/actions/runs/3660420103/jobs/6188235179#step:8:773

```
report: commands[2]> coveralls --service=github
Not on TravisCI. You have to provide either repo_token in .coveralls.yml or set the COVERALLS_REPO_TOKEN env var.
Traceback (most recent call last):
  File "/home/runner/work/armi/armi/.tox/report/lib/python3.10/site-packages/coveralls/cli.py", line 64, in main
    coverallz = Coveralls(token_required,
  File "/home/runner/work/armi/armi/.tox/report/lib/python3.10/site-packages/coveralls/api.py", line 49, in __init__
    self.ensure_token()
  File "/home/runner/work/armi/armi/.tox/report/lib/python3.10/site-packages/coveralls/api.py", line 61, in ensure_token
    raise CoverallsException(
coveralls.exception.CoverallsException: Not on TravisCI. You have to provide either repo_token in .coveralls.yml or set the COVERALLS_REPO_TOKEN env var.
```

I have _no idea_ why they are suddenly mentioning Travis CI.  We have never used it.

I can't tell if our token expired, or they just changed their system, so we need a different token name now.

TBD.
