### ISSUE TITLE
Unit Tests failing on GitHub Actions

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#983]
As you can see, [this build of our Windows unit tests](https://github.com/terrapower/armi/actions/runs/3463436138/jobs/5783668579) failed, with the single message:

```
File "D:\a\armi\armi\armi\reactor\tests\test_assemblies.py", line 597, in test_duplicate
      self._setup_blueprints()
    File "D:\a\armi\armi\armi\reactor\tests\test_assemblies.py", line [58](https://github.com/terrapower/armi/actions/runs/3463436138/jobs/5783668579#step:6:59)9, in _setup_blueprints
      y = textProcessors.resolveMarkupInclusions(
    File "D:\a\armi\armi\armi\utils\textProcessors.py", line 187, in resolveMarkupInclusions
      return _resolveMarkupInclusions(src, root)[0]
    File "D:\a\armi\armi\armi\utils\textProcessors.py", line 247, in _resolveMarkupInclusions
      _processIncludes(src, out, includes, root)
    File "D:\a\armi\armi\armi\utils\textProcessors.py", line 106, in _processIncludes
      raise ValueError(
  ValueError: The !included file, `refSmallSfpGrid.yaml` does not exist from D:\a\armi\armi\armi\tests\detailedAxialExpansion!
```

I fixed it by running the test again. 

It feels like this started happening in the last month. Though pretty rarely. 

And (if my memory serves), it's always with this file: 

> `refSmallSfpGrid.yaml` does not exist from D:\a\armi\armi\armi\tests\detailedAxialExpansion!

This has never happened on Linux and highly suspect it is a problem with the testing infrastructure and not the code.

**Comment by john-science** [comment]
Found it!

@albeanth About 1-in-20 of the times we run the ARMI unit tests on Windows on GitHub they fail (see above). It is rare, so it took me a while to find it.  But the problem are these two lines in the detailed axial expansion tests:

https://github.com/terrapower/armi/blob/ce718557ebca020d380dc5d7daf9006f93565886/armi/tests/detailedAxialExpansion/armiRun.yaml#L43

and

https://github.com/terrapower/armi/blob/ce718557ebca020d380dc5d7daf9006f93565886/armi/tests/detailedAxialExpansion/refSmallReactor.yaml#L17

It is either (a) relative pathing, or (b) Windows/Linux `../` file paths that is the problem. I can't tell yet, but we should fix this.

Tommy thought his branch was broken today and wasted a couple hours looking for a bug in his code that didn't exist. (Just re-running the tests made them pass.)

**Comment by albeanth** [comment]
Whoa! Well that's very interesting. I guess the quick band aid fix is to just copy the files as needed so we don't have to do relative pathing. I'm surprised the relative pathing doesn't work?

**Comment by john-science** [comment]
@albeanth Well, clearly the relative path _should_ work.  It is either a fluke in Windows or a fluke in GitHub-Actions-in-Windows that means it is inconsistent and fails sometimes.

**IDEA 1**: The quick band aid copy-the-files would work. 

**IDEA 2**: Do we even need multiple files for this little test reactor? The `refSmallSfpGrid.yaml` file is pretty short, why not just do it in-line?

https://github.com/terrapower/armi/blob/ce718557ebca020d380dc5d7daf9006f93565886/armi/tests/refSmallSfpGrid.yaml#L1-L11

On that same note, are you even using the shuffling logic in the `refSmallReactorShuffleLogic.py` in that file? 

**IDEA 3**: I wonder if, long term, we really want all these extra input files lying around. If something changes, this is just one more place we have to change it.  Maybe we could just alter the Settings that go into the usual test reactor in code:

https://github.com/terrapower/armi/blob/ce718557ebca020d380dc5d7daf9006f93565886/armi/reactor/tests/test_reactors.py#L131

So they match what is needed in detailed axial expansion.

**Comment by john-science** [comment]
Actually, this is [now failing](https://github.com/terrapower/armi/actions/runs/3743018357/jobs/6354876158) on Linux, and kind of a LOT. 

Same error:

```
ValueError: The !included file, `refSmallSfpGrid.yaml` does not exist from /home/runner/work/armi/armi/armi/tests/detailedAxialExpansion!
```

So, this is suddenly a lot higher priority.

**Comment by albeanth** [comment]
Oh gosh, I just realized that I never responded to these comments. Sorry @john-science! This must have fallen through the cracks. My bad.😞 

I'm glad we were able to get this resolved offline. Thank you for taking the time to do this very necessary cleanup!

**Comment by john-science** [comment]
@albeanth @opotowsky   While I was on a run this morning, I figured it out.

We never solved this bug, and it popped up in yet _another_ new PR. But how?  Well, if we look at the [stack trace](https://github.com/terrapower/armi/actions/runs/3745423951/jobs/6359846174):

```
Traceback (most recent call last):
  File "/home/runner/work/armi/armi/armi/reactor/tests/test_assemblies.py", line 597, in test_duplicate
    self._setup_blueprints()
  File "/home/runner/work/armi/armi/armi/reactor/tests/test_assemblies.py", line 590, in _setup_blueprints
    y, pathlib.Path(self.cs.inputDirectory)
  File "/home/runner/work/armi/armi/armi/utils/textProcessors.py", line 187, in resolveMarkupInclusions
    return _resolveMarkupInclusions(src, root)[0]
  File "/home/runner/work/armi/armi/armi/utils/textProcessors.py", line 247, in _resolveMarkupInclusions
    _processIncludes(src, out, includes, root)
  File "/home/runner/work/armi/armi/armi/utils/textProcessors.py", line 108, in _processIncludes
    fName, root
ValueError: The !included file, `refSmallSfpGrid.yaml` does not exist from /home/runner/work/armi/armi/armi/tests/detailedAxialExpansion!
```

We see the detailed axial expansion test bug we thought we fixed actually popped up in **`test_assemblies.py`**!

This is a classic parallelization problem: a race condition. Somehow the axial expansion tests are affecting OTHER tests, but only some times.  How, you ask?

> `setMasterCs()` / `getMasterCs()` is being called in axial expansion tests!

This sets the case settings objects for ALL other tests that happen to be running at that moment. D'oh!

> The only solution is to remove `getMasterCs()` / `setMasterCs()` from the axial expansion tests.

**Comment by opotowsky** [comment]
😮 

WELL THEN!

**Comment by opotowsky** [comment]
FYI because I only learned this recently: 
Anything that calls `loadTestReactor` calls `setMasterCs`

**Comment by albeanth** [comment]
Ah duh. Ok. 

`loadTestReactor` gets called across 9 different tests in `armi/reactor`. Is the failure being in test_axialExpansionChanger.py repeatable? Or could the failure vary across the different files? 

```bash
C:\Users\aalberti\codes\nala\framework\armi\reactor (main ) > grep -riI --line-number "loadTestReactor"
converters/parameterSweeps/tests/test_paramSweepConverters.py:33:from armi.reactor.tests.test_reactors import loadTestReactor
converters/parameterSweeps/tests/test_paramSweepConverters.py:42:        self.o, self.r = loadTestReactor(TEST_ROOT)
converters/tests/test_axialExpansionChanger.py:28:from armi.reactor.tests.test_reactors import loadTestReactor, reduceTestReactorRings
converters/tests/test_axialExpansionChanger.py:557:        o, self.r = loadTestReactor(TEST_ROOT)
converters/tests/test_axialExpansionChanger.py:830:        o, r = loadTestReactor(
converters/tests/test_axialExpansionChanger.py:838:        oCold, rCold = loadTestReactor(
converters/tests/test_blockConverter.py:27:from armi.reactor.tests.test_reactors import loadTestReactor, TEST_ROOT
converters/tests/test_blockConverter.py:94:            loadTestReactor(TEST_ROOT)[1]
converters/tests/test_blockConverter.py:125:            loadTestReactor(TEST_ROOT)[1]
converters/tests/test_blockConverter.py:130:        block = loadTestReactor(TEST_ROOT)[1].core.getFirstBlock(Flags.CONTROL)
converters/tests/test_blockConverter.py:173:            loadTestReactor(TEST_ROOT)[1]
converters/tests/test_blockConverter.py:197:        r = loadTestReactor(TEST_ROOT, inputFileName="zpprTest.yaml")[1]
converters/tests/test_geometryConverters.py:31:from armi.reactor.tests.test_reactors import loadTestReactor, reduceTestReactorRings
converters/tests/test_geometryConverters.py:41:        self.o, self.r = loadTestReactor(TEST_ROOT)
converters/tests/test_geometryConverters.py:135:        self.o, self.r = loadTestReactor(TEST_ROOT)
converters/tests/test_geometryConverters.py:276:        self.o, self.r = loadTestReactor(TEST_ROOT)
converters/tests/test_geometryConverters.py:311:        self.o, self.r = loadTestReactor(TEST_ROOT)
converters/tests/test_meshConverters.py:20:from armi.reactor.tests.test_reactors import loadTestReactor
converters/tests/test_meshConverters.py:31:        self.o, self.r = loadTestReactor(TEST_ROOT)
converters/tests/test_uniformMesh.py:27:from armi.reactor.tests.test_reactors import loadTestReactor, reduceTestReactorRings
converters/tests/test_uniformMesh.py:38:        self.o, self.r = loadTestReactor(
converters/tests/test_uniformMesh.py:63:        self.o, self.r = loadTestReactor(
converters/tests/test_uniformMesh.py:223:        cls.o, cls.r = loadTestReactor(TEST_ROOT, customSettings={"xsKernel": "MC2v2"})
converters/tests/test_uniformMesh.py:292:        self.o, self.r = loadTestReactor(
converters/tests/test_uniformMesh.py:377:        self.o, self.r = loadTestReactor(
converters/tests/test_uniformMesh.py:551:        self.o, self.r = loadTestReactor(
tests/test_assemblies.py:1036:        self.o, self.r = test_reactors.loadTestReactor(TEST_ROOT)
tests/test_reactors.py:138:def loadTestReactor(
tests/test_reactors.py:243:        self.o, self.r = loadTestReactor(
tests/test_reactors.py:571:        _o2, r2 = loadTestReactor(customSettings={"xsKernel": "MC2v2"})
tests/test_reactors.py:868:        o, r = loadTestReactor(
tests/test_zones.py:169:        self.o, self.r = test_reactors.loadTestReactor()
```

**Comment by john-science** [comment]
@albeanth Because of the stack trace, we know that non-axial-expansion tests are getting the axial expansion case settings.  So, that's our root cause.  I believe this has always been a potential problem, but you were the first person to throw different blueprint files into the test reactor.

@opotowsky @albeanth I think the only _real_ solution is to remove `setMasterCs()` from `loadTestReactor()`.  That will _have_ to get done.  But a quicker and easier solution would be to just re-write the axial expansion tests to not use `loadTestReactor()`.

Or maybe we add a flag to `loadTestReactor()` to not use `setMasterCs()`, so we can slowly away from the bad pathway until nothing is using it.  

Just spit-balling, I'm on my phone.

**Comment by opotowsky** [comment]
Ah I was wondering if it was the order in which the tests were being executed (which may still be the case)....but its the new blueprints really messing thigs up.

**Comment by john-science** [comment]
The ORDER is really the key. That's the fun part of a race condition. If the parallel tests are run in some orders, the tests pass. But if they are run in other tests, they fail.  It all depend on if the axial expansion blueprints are loaded into memory at the wrong time.

**Comment by albeanth** [comment]
> But a quicker and easier solution would be to just re-write the axial expansion tests to not use loadTestReactor().

I should be able to do this after the holiday. A benefit is that I can make it as light as possible and therefore _much_ faster.

Though I think ultimately, the best/ideal solution (as John points out) is to remove `setMasterCs()` from `loadTestReactor()`.

**Comment by john-science** [comment]
@albeanth  It's after the holidays!

What do you think?

**Comment by albeanth** [comment]
I think there needs to be more time in the day 😄 

If it is becoming blocking for PRs and testing, I can move it up the priority list. Otherwise, it would be great it this could wait until ~mid next week?

**Comment by john-science** [comment]
This hasn't happened in a while. Can this ticket be closed?

@albeanth @opotowsky Perhaps a question for while I'm out next week.

**Comment by albeanth** [comment]
I'm fine with it. I don't think I actually ever experienced it, personally. But the whole globalCs problem persists outside this issue.

**Comment by opotowsky** [comment]
Global Cs

Global nuclideBases

we got problems. But maybe new ticket fodder
